baseURL = 'https://weblog.zianliu66.me'
languageCode = 'en-us'
title = 'Zian Liu'
theme = 'papermod'


enableRobotsTXT = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production" # to enable google analytics, opengraph, twitter-cards and schema.
description = "ExampleSite description"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
DateFormat = "2006-01-02"
defaultTheme = "dark" # dark, light
disableThemeToggle = true

#  ShowReadingTime: true
#  ShowShareButtons: true
#  ShowPostNavLinks: true
#  ShowBreadCrumbs: true
#  ShowCodeCopyButtons: false
#  ShowWordCount: true
#  ShowRssButtonInSectionTermList: true
#  UseHugoToc: true
#  disableSpecial1stPost: false
#  disableScrollToTop: false
#  comments: false
#  hidemeta: false
#  hideSummary: false
#  showtoc: false
#  tocopen: false

  [params.assets]
  disableHLJS = true # to disable highlight.js
  disableFingerprinting = true
  #  favicon: "<link / abs url>"
  #  favicon16x16: "<link / abs url>"
  #  favicon32x32: "<link / abs url>"

  #[params.label]
  #  text: "Home"
  #  icon: /apple-touch-icon.png
  #  iconHeight: 35

  [[params.socialIcons]]
  name = "GitHub"
  url = "https://github.com/"

  #cover:
  #  hidden: true # hide everywhere but not in structured data
  #  hiddenInList: true # hide on list pages and home
  #  hiddenInSingle: true # hide on single page

  #editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

[menu]
  [[menu.main]]
  identifier = "categories"
  name = "categories"
  url = "/categories/"
  weight = 10
  #  - identifier: tags
  #    name: tags
  #    url: /tags/
  #    weight: 20
  #  - identifier: example
  #    name: example.org
  #    url: https://example.org
  #    weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
#pygmentsUseClasses: true
#markup:
#  highlight:
#    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
